version: '3.8'

services:
frontend:
    build: .
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - gallery-photos:/app/uploads
    restart: always

volumes:
  - ./backend:/app
  - gallery-photos:/app/uploads
  - ./backend/trips.db:/app/trips.db